server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: PLAINTEXT://192.168.0.29:9092
    consumer:
      group-id: kafka2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer